version: '3'
services:
  redis-server:
    image: 'redis'

  node-app:
    restart: on-failure
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
    - /app/node_modules
    - .:/app
      